- collection:
      description: Collection of available <<resourcePathName>>
      get:
        description: Get a list of <<resourcePathName>>.
        responses:
          200:
            body:
              application/json:
                schema: <<resourcePathName>>
                example: |
                  <<exampleCollection>>